# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 20:36
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('nazwa', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=50)),
                ('typ', models.CharField(max_length=15)),
                ('otwarty', models.BooleanField()),
                ('zwiedzanie', models.BooleanField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
            ],
        ),
    ]
